# Generated by Django 6.1 on 2026-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('origem', models.CharField(choices=[('hire_modal', 'Modal Contratar'), ('contato', 'Seção Contato'), ('outro', 'Outro')], default='hire_modal', max_length=32, verbose_name='Origem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('arquivado', 'Arquivado')], default='novo', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
