# Generated by Django 6.1 on 2026-08-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_migrate_leads_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='maps_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL Maps'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='website',
            field=models.CharField(blank=True, max_length=300, verbose_name='Website'),
        ),
    ]
