# Generated by Django 6.1 on 2026-09-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cliente_website_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='categoria',
            field=models.CharField(choices=[('odontologia', 'Odontologia'), ('geral', 'Geral')], default='geral', max_length=32, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='mockup',
            name='tipo',
            field=models.CharField(choices=[('galeria', 'Galeria'), ('landing', 'Landing')], default='galeria', max_length=32, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockups', to='crm.cliente', verbose_name='Cliente'),
        ),
    ]
