# Generated by Django 6.1 on 2026-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('stack', models.CharField(blank=True, help_text='Tecnologias separadas por vírgula', max_length=255, verbose_name='Stack')),
                ('url', models.URLField(blank=True, verbose_name='URL do projeto')),
                ('capa', models.ImageField(blank=True, upload_to='projects/', verbose_name='Capa')),
                ('destaque', models.BooleanField(default=True, verbose_name='Destaque na landing')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['ordem', '-created_at'],
            },
        ),
    ]
